name: Build and Push Lambda Image to ECR

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Build & Push to ECR
    runs-on: ubuntu-latest
    env:
      ECR_REGISTRY: 637423381395.dkr.ecr.ap-northeast-1.amazonaws.com
      REPOSITORY_NAME: fastapi-agent
      CLUSTER_NAME: fastapi-cluster
      SERVICE_NAME: fastapi-service
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Set up ECR variables
        run: |
          ECR_REGISTRY=637423381395.dkr.ecr.ap-northeast-1.amazonaws.com
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1

      - name: Login to Amazon ECR
        run: |
          aws ecr get-login-password --region ap-northeast-1 \
          | docker login --username AWS --password-stdin $ECR_REGISTRY

      - name: Build Docker image
        run: |
          docker build -t $ECR_REGISTRY/$REPOSITORY_NAME:latest .

      - name: Push Docker image to ECR
        run: |
          docker push $ECR_REGISTRY/$REPOSITORY_NAME:latest

      # - name: Force new deployment on ECS
      #   run: |
      #     aws ecs update-service \
      #       --cluster $CLUSTER_NAME \
      #       --service $SERVICE_NAME \
      #       --force-new-deployment
